### ISSUE TITLE
Error during conda install -y -c simplect clojupyter (Windows, Anaconda/Python 2)

### ISSUE THREAD

**Issue by vjktm** [clojupyter/clojupyter#101]
Hi All,
I get the following when I try to conda install clojupyter:
Does clojupyter need Anaconda3 or will it work with Anaconda2?  Could it be a problem in my environment?   I do not see the C:\ProgramData\Anaconda2\pkgs\clojupyter-0.2.3-1\ folder in my file system.
Thanks in advance for your help.
Vijaya

(base) PS C:\WINDOWS\system32> conda install -y -c simplect clojupyter
Collecting package metadata (current_repodata.json): done
Solving environment: done
 
## Package Plan ##
 
  environment location: C:\ProgramData\Anaconda2
 
  added / updated specs:
    - clojupyter
 
 
The following NEW packages will be INSTALLED:
 
  clojupyter         simplect/win-64::clojupyter-0.2.3-1
  maven              pkgs/main/win-64::maven-3.6.0-0
  openjdk            pkgs/main/win-64::openjdk-8.0.152-h7382acf_1
 
 
Preparing transaction: done
Verifying transaction: done
Executing transaction: | "post-link.bat: JARFILE=C:\ProgramData\Anaconda2\pkgs\clojupyter-0.2.3-1\info\recipe\install-items\clojupyter-standalone.jar"
Error: Could not find or load main class clojupyter.cmdline
 
done
(base) PS C:\WINDOWS\system32>

**Comment by klausharbo** [comment]
I am glad it worked out for you.  Thanks for the report.  Hope you'll enjoy Clojupyter!

-Klaus.
