### ISSUE TITLE
Clarify that clojupyter (v.future) supports only Python 3.5 or later, not Python 3.4

### ISSUE THREAD

**Issue by rbeesley** [clojupyter/clojupyter#106]
More as an FYI than a bug, [...notebook 6 supports only Python 3.5 or later, not Python 3.4](https://github.com/jupyter/notebook/pull/4875).

I saw that there was another bug filed earlier (#101) about trying to use Clojupyter on Python 2. With Jupyter Notebook 6, all support for that will be dropped, so any release made which targets that platform should also drop support for less than 3.5, to remain consistent and to reduce the number of variations.

**Comment by klausharbo** [comment]
Closed.
