### ISSUE TITLE
Error evaluating statement

### ISSUE THREAD

**Issue by vikeri** [clojupyter/clojupyter#108]
I get the following error sometimes when I try to evaluate a big statement:

```
ERROR [clojupyter.kernel.core:?] - clojure.lang.ArityException: Wrong number of args (0) passed to: clojure.core/max
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.RestFn.invoke (RestFn.java:399)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    clojupyter.kernel.cljsrv.nrepl_comm$stacktrace_string.invokeStatic (nrepl_comm.clj:30)
    clojupyter.kernel.cljsrv.nrepl_comm$stacktrace_string.invoke (nrepl_comm.clj:21)
    clojupyter.kernel.cljsrv.nrepl_comm$set_stacktrace_BANG_.invokeStatic (nrepl_comm.clj:149)
    clojupyter.kernel.cljsrv.nrepl_comm$set_stacktrace_BANG_.invoke (nrepl_comm.clj:142)
    clojupyter.kernel.cljsrv.nrepl_comm$nrepl_eval_STAR_.invokeStatic (nrepl_comm.clj:182)
    clojupyter.kernel.cljsrv.nrepl_comm$nrepl_eval_STAR_.invoke (nrepl_comm.clj:167)
    clojupyter.kernel.cljsrv.nrepl_comm.NreplComm.nrepl_eval (nrepl_comm.clj:198)
    clojupyter.kernel.middleware.execute$submit_eval_request.invokeStatic (execute.clj:23)
    clojupyter.kernel.middleware.execute$submit_eval_request.invoke (execute.clj:21)
    clojupyter.kernel.middleware.execute$fn__18026.invokeStatic (execute.clj:37)
    clojupyter.kernel.middleware.execute/fn (execute.clj:33)
    clojupyter.kernel.transport$handler_when$fn__15439$fn__15440.invoke (transport.clj:89)
    clojupyter.kernel.middleware.base$wrap_busy_idle$fn__16237.invoke (base.clj:79)
    clojupyter.kernel.transport$transport_layer$fn__15421$fn__15423.invoke (transport.clj:60)
```

**Comment by klausharbo** [comment]
Hi Viktor -

You are not providing much information about your setup, but from the stacktrace you provide it looks to me like you are calling the `max` function with no arguments, which is not allowed in Clojure.

-Klaus.

**Comment by vikeri** [comment]
Hi, ok. I didn't see any reference to any of my code in the stacktrace and I never use `max` in my code. Is there a way to track the error back to the origin?

**Comment by klausharbo** [comment]
I think the exception is thrown by code in `clojupyter.kernel.nrepl-comm`, possibly because there are no references to clojure files in the stacktrace:

```
(defn- stacktrace-string
  "Return a nicely formatted string."
  [msg]
  (when-let [st (:stacktrace msg)]
    (let [clean (->> st
                     (filter (fn [f] (not-any? #(= "dup" %) (:flags f))))
                     (filter (fn [f] (not-any? #(= "tooling" %) (:flags f))))
                     (filter (fn [f] (not-any? #(= "repl" %) (:flags f))))
                     (filter :file))
          max-file (apply max (map count (map :file clean)))
          max-name (apply max (map count (map :name clean)))]
      (map #(format (str "%" max-file "s: %5d %-" max-name "s")
                    (:file %) (:line %) (:namery to  %))
           clean))))
```

as the first line with `max` called is line 30 which appears in the stacktrace.  I don't think I have seen that before, and don't know when it would occur.  The code above clearly assumes that this would never happen, so I consider it an error in Clojupyter.

It may not help much, but - since it appears that the problem is cause in printing the stacktrace - you could try to disable stacktrack printing which can be done with

```
(clojupyter.kernel.stacktrace/set-print-stacktraces! false)
```

This might help you find the error that caused the throw in first place.

Stack trace printing can also be controlled in the Clojupyter config file (`~/Library/Preferences/clojupyter.edn` on Mac, `~/.config/clojupyter.edn` on Linux) by having:

```
{:print-stacktraces? false}
```
in the file.

I am curious how this could happen, so if you could share more about your setup and code, I'd be interested.

**Comment by vikeri** [comment]
Found that the error was caused by calling `clojure.pprint/print-table`. So that was on my part. The only questions for Clojupyter are hence:
- How can one have the stack-trace correctly reflect where the error happened?
- Is there a way to recover from an error without having to restart the kernel?

**Comment by vikeri** [comment]
They should probably be different issues.

**Comment by klausharbo** [comment]
I don't know why you're seeing this in your setup, a normal stack trace print would succeed and give you whatever it has to offer, e.g.  if I do

```
(/ 1 0)
```

I get

```
Execution error (ArithmeticException) at user/eval4092 (REPL:1).
Divide by zero
Numbers.java:   188 clojure.lang.Numbers/divide                            
    core.clj:  3214 clojure.core$eval/invokeStatic                         
    core.clj:  3210 clojure.core$eval/invoke                               
    main.clj:   437 clojure.main$repl$read_eval_print__9086$fn__9089/invoke
    main.clj:   458 clojure.main$repl$fn__9095/invoke                      
    main.clj:   368 clojure.main$repl/doInvoke                             
 RestFn.java:  1523 clojure.lang.RestFn/invoke                             
    AFn.java:    22 clojure.lang.AFn/run                                   
    AFn.java:    22 clojure.lang.AFn/run                                   
 Thread.java:   748 java.lang.Thread/run 
```

as the cell evaluation result, the kernel continues to run, I fix the error and continue.  I think that is what we want.
