### ISSUE TITLE
Clojupyter does not print nREPL port anymore

### ISSUE THREAD

**Issue by thiagokokada** [clojupyter/clojupyter#113]
Until version 0.2.3, Clojupyter used to print the nREPL port to console, allowing you to connect to the current notebook using i.e. CIDER. I think it was implemented here: https://github.com/clojupyter/clojupyter/pull/79

Now in the current version (0.3.1) it stopped doing this. Can we get it back?

**Comment by klausharbo** [comment]
I bumped the printing of the NREPL connection info to loglevel `info`.  If you put

```
{:log-level :info}
```

in `clojupyter.edn` in `~/Library/Preferences` on  Mac and `~/.config/` on Linux it will print the connection info.

**Comment by thiagokokada** [comment]
@klausharbo This worked, thanks!
