### ISSUE TITLE
Bad Environment when calling list-installs

### ISSUE THREAD

**Issue by MattFanto** [clojupyter/clojupyter#118]
I'm trying to use clojupyter as a library inside anaconda3 jupyter notebook on WSL, but I'm facing the following issue when calling `clj -m clojupyter.cmdline list-installs` or `clojure -m clojupyter.cmdline install`

`
(-main) Error occurred: clojure.lang.ExceptionInfo: Internal error: Bad install-env {:install-env {:local/resource-map {"clojupyter/assets/conda-build/pre-unlink.sh" #object[java.net.URL 0x3ce7490a "jar:file:/home/matt/.m2/repository/clojupyter/clojupyter/0.2.3/clojupyter-0.2.3.jar!/clojupyter/assets/conda-build/pre-unlink.sh"], "clojupyter/assets/conda-build/post-link.bat" #object[java.net.URL 0x4768b95c "jar:file:/home/matt/.m2/repository/clojupyter/clojupyter/0.2.3/clojupyter-0.2.3.jar!/clojupyter/assets/conda-build/post-link.bat"], "clojupyter/assets/logo-64x64.png" #object[java.net.URL 0x1530d0f2 "jar:file:/home/matt/.m2/repository/clojupyter/clojupyter/0.2.3/clojupyter-0.2.3.jar!/clojupyter/assets/logo-64x64.png"], "clojupyter/assets/conda-build/post-link.sh" #object[java.net.URL 0x7573c7b5 "jar:file:/home/matt/.m2/repository/clojupyter/clojupyter/0.2.3/clojupyter-0.2.3.jar!/clojupyter/assets/conda-build/post-link.sh"]}, :version/version-map #:version{:major 0, :minor 2, :incremental 3}, :local/jarfiles (#object[java.io.File 0x73da7f08 "/mnt/c/Users/m.fantoni/xxx/clojupyter-standalone.jar"]), :local/user-homedir #object[java.io.File 0x717a8a76 "/home/matt"], :local/filemap #filemap{#object[java.io.File 0x73da7f08 "/mnt/c/Users/m.fantoni/xxx/clojupyter-standalone.jar"]
 :filetype/file,
 #object[java.io.File 0x2e85e3f1 "/usr/local/share/jupyter/kernels"]
 :filetype/directory,
 #object[java.io.File 0x6e090aaa "/home/matt/.local/share/jupyter/kernels"]
 :filetype/directory}, :local/logo-resource "clojupyter/assets/logo-64x64.png", :local/user-kernel-dir #object[java.io.File 0x6e090aaa "/home/matt/.local/share/jupyter/kernels"], :local/host-kernel-dir #object[java.io.File 0x2e85e3f1 "/usr/local/share/jupyter/kernels"], :local/convert-exe nil, :local/default-ident "clojupyter-0.2.3", :local/installed-kernels {}}, :explain-str "nil - failed: (π instance? java.io.File) in: [:local/convert-exe] at: [:local/convert-exe] spec: :local/file\n", :msg "Internal error: Bad install-env"}
`

My deps.edn

`{:paths     ["resources" "src" "module/kotr/src"]
 :deps      {org.clojure/clojure            {:mvn/version "1.10.1"}
             cheshire                       {:mvn/version "5.9.0"}
             org.clojure/tools.logging      {:mvn/version "0.5.0"}
             org.clojure/tools.reader       {:mvn/version "1.3.2"}
             org.clojure/data.csv           {:mvn/version "0.1.4"}
             ch.qos.logback/logback-classic {:mvn/version "1.1.7"}
             clojupyter                     {:mvn/version "0.2.3"}
...`

The same doesn't happens if I run the command from the anaconda jar directly

`java -cp ~/anaconda3/share/jupyter/kernels/conda-clojupyter/clojupyter-standalone.jar clojupyter.cmdline install --ident mykernel --jarfile clojupyter-standalone.jar`

Unfortunately, this error is quite difficult to read and I can't figure out any possible troubleshooting solution except for:
1) Removing anaconda3 completely (still facing it)
2) Reinstalling anacoda3 (still facing it)
3) Installing clojupyter with anancoda3 (still facing it)

**Comment by codrinc** [comment]
looks similar to this issue: #103.
installing `imagemagick` helps, as suggested here: https://github.com/clojupyter/clojupyter/issues/103#issuecomment-564259211.

**Comment by nighcoder** [comment]
@MattFanto, if I understand correctly, the solution proposed by @codrinc worked for you.

I'm closing this, but feel free to reopen it if you're still having issues.
