### ISSUE TITLE
Clojupyter doesn't install (space in file path)

### ISSUE THREAD

**Issue by FrancisKing3** [clojupyter/clojupyter#121]
Clojupyter doesn't work for me. There appears to be a problem with the fact that my user folder contains a space.

![image](https://user-images.githubusercontent.com/47246424/82751568-03190e00-9db0-11ea-9d40-dbae747e6093.png)

**Comment by krukow** [comment]
Hey @FrancisKing3  - apologies for the late reply - I'm maintaining this in my spare time.

I've been looking into this and unfortunately I can no longer support installation via conda. Instead I recommend building the latest version locally via the following commands (requires [clojure CLI and deps tools](https://clojure.org/guides/deps_and_cli)):

## Build

Checkout [this repo](https://github.com/clojupyter/clojupyter) on the master branch and build an uberjar:

Building an uberjar:

```
clj -T:build uber

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
target/clojupyter-0.4.321-standalone.jar
```

## Install kernel

```
clj -M -m clojupyter.cmdline install --jarfile target/clojupyter-0.4.321-standalone.jar --ident clojupyter-0.4.321
```

Verify:

```
clj -M -m clojupyter.cmdline list-installs

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Clojupyter v0.4.321@321 - All Clojupyter kernels

    |              IDENT |                                          DIR |
    |--------------------+----------------------------------------------|
    | clojupyter-0.4.321 | ~/Library/Jupyter/kernels/clojupyter-0.4.321 |

exit(0)
```

## Check that everything works

Install jupyterlab if you haven't already. On MacOS you might do:
```
brew install jupyterlab
```

Validate that it's working:
```
jupyter lab --version
4.0.9
```


Now you can try a console:

```
jupyter-console --kernel=clojupyter-0.4.321
WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Jupyter console 6.6.3

Clojupyter (0.4.321)
```

Or you can run in jupyter lab (from this repo):

```
jupyter lab
```

then open a file like: examples/demo-clojupyter.ipynb and run all cells.

## Use clojupyter as a library as part of another program/library

You can also use this as a library - here's an example: https://github.com/krukow/edmondson

**Comment by krukow** [comment]
Closing: I will not be able to support releasing to Conda and all users should be familar with clojars since this is a clojure project.
