### ISSUE TITLE
Dependency conflicts due to Uberjar/AOT compilation

### ISSUE THREAD

**Issue by metasoarous** [clojupyter/clojupyter#129]
Hello

First off, let me thank you for your work on this project. It's great to be able to point newcomers to the Clojure space (especially from data science backgrounds) to Clojupyter as a way to get started.

My data visualization (and generally, scientific documentation) library [Oz](https://github.com/metasoarous/oz) has a `oz.notebook.clojupyter` namespace which allows users to utilize Vega-Lite & Vega data visualizations (and a small set of additional goodies). In the past, I've (and other Oz users) had numerous issues with the many dependencies in Clojupyter conflicting with other dependencies. This problem seems to be compounded by the fact that Clojupyter uses Uberjar/AOT compilation.

For this reason I have made the Clojupyter an optional dependency of Oz, since I think most users are using it outside of Clojupyter. However, while trying to generate documentation for the project with [codox](https://github.com/weavejester/codox), I have found that I'm unable to do so because of conflicts with the `hiccup` library (for issue details, please see: https://github.com/weavejester/codox/issues/194).

Is there a good reason that Clojupyter has to be Uberjar/AOT compiled? Would it be possible to get a second artifact that isn't AOT compiled? In my case, I don't really even need all of Clojupyter. I just need to be able to implement `clojupyter.protocol.mime-convertible/PMimeConvertible`, and I'm guessing this is the case for a lot of libraries which wish to extend Clojupyter, and that this would make their lives easier as well. Would it make sense to release something along the lines of a stripped down `clojupyter-lib` or `clojupyter-mimetype` library to ease this pain?

Unfortunately, this is holding me up from releasing the first non-alpha version of Oz in a while, as I want to be able to do so with solid docs, and have been having trouble with cljdoc as well, which I was using previously.

Please let me know if you have any questions or wish to discuss further.

Thanks again

**Comment by nighcoder** [comment]
The problem with packing all in a uberjar was something I've hit while working on ipywidgets and later on ipyleaflet for Clojupyter. I've solved that problem by breaking the uberjar into multiple jars, one for Clojupyter and one for each of Clojupyter's dependencies. If that helps you, check out the fork on my page, since I'm not one of the maintainers.

Unfortunately, for all I know, there's no way to only use part of Clojupyter. It would be a step in the right direction, since even after all the stuff I removed from the jar, it's still a huge jar of 8 MB, double that of Clojure.

**Comment by metasoarous** [comment]
Hey @nighcoder. Thanks for the quick reply.

Have you published these jars to Clojars or anywhere else? I would consider pointing to these, but worry a little bit about pointing to non-canonical artifacts, as I can imagine it causing issues as the project drifts.

I hear you that there's no way to use just one part of Clojupyter in general, but it should be possible to peel off the protocol definitions as a separate artifact so that library authors such as ourselves can refer to these without having to pull in the entire Clojupyter project. Then Clojupyter and our libs can all refer to the same protocols.

This doesn't entirely solve the problem though, because if Clojupyter is still being AOT compiled, once our libraries get _used_ with Clojupyter, we're still likely to hit some of these compilation conflicts. So again, while a separate protocol artifact would be helpful, ultimately it would be best if Clojupyter could be put together like a regular Clojure jar. There may be technical reasons why this is difficult or problematic, but I think it's worth having the discussion.

Thanks again!

**Comment by nighcoder** [comment]
As much as I would like to not let my work go to waste, I think it's best if you don't use my version on your project. I did the changes that I need to get rid of the uberjar and to allow sharing of libraries (moving from static dynamic compilation in C speak) to ease the development of third party plugins for Clojupyter. I never intended to make a fork of Clojupyter, so I never publish the jar, nor did I advertise my version anywhere. If you want to try it out, you'll have to compile it yourself, which should be as simple as typing `lein metajar`.
That being said, I think it makes most sense for you to target the Clojupyter version that has the most users, no matter how advanced a fork is.

> I hear you that there's no way to use just one part of Clojupyter in general, but it should be possible to peel off the protocol definitions as a separate artifact so that library authors such as ourselves can refer to these without having to pull in the entire Clojupyter project. Then Clojupyter and our libs can all refer to the same protocols.

That's definitively possible, but that requires some (a lot of?) work so I wouldn't hold my breath. See #128 which failed to get a single comment in two months as a possible explanation for my cynicism.

The more I think about your problem, the less I think it has anything to do with the way Clojupyter is compiled. You will have issues as long as your dependency tree has multiple versions of the same artifact. In fact, if you list Clojupyter in your dependencies, you'll pull a thin jar from Clojars, not the whole uberjar.

**Comment by krukow** [comment]
@metasoarous - apologies for the late reply - I'm maintaining this in my spare time. How did this go?


You can also use this as a library/jar - here's an example: https://github.com/krukow/edmondson 

does that help?
