### ISSUE TITLE
Error in notebook whereas the same code runs fine in gorilla-repl.

### ISSUE THREAD

**Issue by mmwaikar** [clojupyter/clojupyter#133]
Hello team@nextjournal,

I was trying to run code from my open-source library (SqlForCql) - https://github.com/mmwaikar/SqlForCql/tree/develop in next journal but I get the below error:

![image](https://user-images.githubusercontent.com/103141/125030396-b45c2f80-e0a8-11eb-9ba1-c04cc56b5310.png)

The same code however works in gorilla-repl. An example run (in gorilla-repl) is attached as a zip file.
[get-all-ex.zip](https://github.com/clojupyter/clojupyter/files/6789067/get-all-ex.zip)

**Comment by nighcoder** [comment]
@mmwaikar, it looks like your issue is not related to Clojupyter.

Please contact the team behind nextjournal if you still have issues with it. Afaik, nextjournal doesn't use Clojupyter for its notebooks, so we can't help you with your problem.
