### ISSUE TITLE
Update hiccup library

### ISSUE THREAD

**Issue by metasoarous** [clojupyter/clojupyter#141]
I'm encountering problems with the development environment in [Oz](https://github.com/metasoarous/oz) (specifically the shadow-cljs + devcards setup) due to clojupyter being AOT compiled against an older version of hiccup:

https://github.com/metasoarous/oz/issues/165

The simple solution to this would be to bump the hiccup version in Clojupyter to `2.0.0-alpha2`. Please let me know if you'd accept a PR and be able to cut a release for this.

Longer term (and more generally), it would be great to hear back on #129, since this is not the first time that issues have cropped up with clojupyter's AOT compilation creating issues for Oz and other libraries.

Thanks in advance

**Comment by krukow** [comment]
@metasoarous thanks for writing up the issue. We're currently in the process of restructuring how this project is deployed (see https://github.com/clojupyter/clojupyter/pull/128 - while this is closed we are still planning on going down this path). In the mean time, I'd be happy to release a version with upgraded hiccup (we also have a different request to cut a new release https://github.com/clojupyter/clojupyter/pull/135#issuecomment-917045369).

I'm currently working with the original maintainers to better understand the release process, but that should be sorted soon.  Feel free to cut a PR with the deps upgrade.

**Comment by krukow** [comment]
@metasoarous no need to create the PR, I've published a 0.3.3-alpha2 release baed off the 0.3.2 branch but with the fixes for latest version of jupyter lab and `hiccup` `2.0.0-alpha2`.

I'm closing this issue - feel free to reopen if it's not working for you.

Alpha release: https://clojars.org/clojupyter/versions/0.3.3-alpha2

**Comment by metasoarous** [comment]
Wonderful! Thanks so much for your rapid assistance here @krukow!

I just tried out `0.3.3-alpha2`, and it does seem to have fixed the problem.

Thanks again!
