### ISSUE TITLE
depstar is deprecated and archived; switch to tools.build

### ISSUE THREAD

**Issue by seancorfield** [clojupyter/clojupyter#160]
`depstar` has been deprecated and archived for six month now; I'm encouraging everyone to switch to `tools.build`. My `build-clj` wrapper makes it easier to switch.

**Comment by krukow** [comment]
thanks @seancorfield, I appreciate the heads up. I was already planning to move to `tools.build` and `tools.deps` once a larger refactor is merged: https://github.com/clojupyter/clojupyter/pull/147 

cc: @nighcoder

**Comment by krukow** [comment]
Fixed with latest state on master branch - we've (finally) migrated to tools.build
