### ISSUE TITLE
sqllite exception on kernel start – Apple M1 Mac

### ISSUE THREAD

**Issue by dustingetz** [clojupyter/clojupyter#163]
Fix was to shadow `org.xerial/sqlite-jdbc {:mvn/version "3.39.2.0"}` in my kernel uberjar's deps.edn, per latest coordinates from https://github.com/xerial/sqlite-jdbc. 

`clojupyter {:mvn/version "0.3.3"}` 

Root error was:
```
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
```
This was buried in a kernel restart loop upon launch of `mykernel-1` while following [Using Clojupyter as a library](https://github.com/clojupyter/clojupyter/blob/master/doc/library.md)

Related: 
* https://github.com/clojupyter/clojupyter/pull/143
* https://github.com/clojupyter/clojupyter/issues/162

**Comment by krukow** [comment]
@dustingetz - I've pushed a release of 0.3.5 from https://github.com/clojupyter/clojupyter/tree/v0.3.5 - could you see if this works for you?

**Comment by krukow** [comment]
@dustingetz  

Please install release 0.3.6 from https://clojars.org/clojupyter.

This is tested and working. 

Closing this issue - please reopen if you can reproduce the problem. If you reopen, please help me with instructions to reproduce from a clean install
