### ISSUE TITLE
Conda simplect release channel only has at latest clojuputer 0.3.2 and is behind in releases

### ISSUE THREAD

**Issue by rbeesley** [clojupyter/clojupyter#169]
```
(jupyter) > conda search -c simplect clojupyter
Loading channels: done
# Name                       Version           Build  Channel
clojupyter                     0.2.3               1  simplect
clojupyter                     0.2.3               2  simplect
clojupyter                     0.3.0               1  simplect
clojupyter                     0.3.1               1  simplect
clojupyter                     0.3.2               1  simplect
(jupyter) >
```

0.3.6 is the latest available in GitHuib as of writing this bug report.

**Comment by rbeesley** [comment]
Looks like it would need to be changed here: https://anaconda.org/simplect/clojupyter

**Comment by krukow** [comment]
@klausharbo I've never released to conda (I use jars for my projects). Can you help with this?

**Comment by klausharbo** [comment]
I did some fairly detailed notes on the steps needed to build a release and upload it to anaconda.org, see attachment.  I haven't look at Clojupyter in quite a while some I'm not sure what the build process looks like at this point.  I have the credentials for simplect account at anaconda.org and am happy to assist in uploading if anybody can build and send the artifacts that need uploading.

[clojupyter-release-process-notes--2020-03-01--0.3.2.1.html.tar.gz](https://github.com/clojupyter/clojupyter/files/11714858/clojupyter-release-process-notes--2020-03-01--0.3.2.1.html.tar.gz)

**Comment by krukow** [comment]
@klausharbo I've tried my way on this (building on a Mac M1):

Sha: 0a3df04790e626102743175b3e89e153a554ce15

https://drive.google.com/file/d/1F2nuqTNT0IQ_E0z3WeHjRlRxg9lPfGxx/view?usp=drive_link

**Comment by klausharbo** [comment]
Sorry for the late response, didn't act on the mail immediately and needed to re-set up conda to do the upload.  However, I just uploaded the file to anaconda.org.  Could someone see if it works?  Would be great if we could have linux-64 and win-64 as well.

**Comment by krukow** [comment]
Hey @rbeesley @ca1123 - apologies for the late reply - I'm maintaining this in my spare time.

I've been looking into this and unfortunately I can no longer support installation via conda. Instead I recommend building the latest version locally via the following commands (requires [clojure CLI and deps tools](https://clojure.org/guides/deps_and_cli)):

## Build

Checkout [this repo](https://github.com/clojupyter/clojupyter) on the master branch and build an uberjar:

Building an uberjar:

```
clj -T:build uber

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
target/clojupyter-0.4.321-standalone.jar
```

## Install kernel

```
clj -M -m clojupyter.cmdline install --jarfile target/clojupyter-0.4.321-standalone.jar --ident clojupyter-0.4.321
```

Verify:

```
clj -M -m clojupyter.cmdline list-installs

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Clojupyter v0.4.321@321 - All Clojupyter kernels

    |              IDENT |                                          DIR |
    |--------------------+----------------------------------------------|
    | clojupyter-0.4.321 | ~/Library/Jupyter/kernels/clojupyter-0.4.321 |

exit(0)
```

## Check that everything works

Install jupyterlab if you haven't already. On MacOS you might do:
```
brew install jupyterlab
```

Validate that it's working:
```
jupyter lab --version
4.0.9
```


Now you can try a console:

```
jupyter-console --kernel=clojupyter-0.4.321
WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Jupyter console 6.6.3

Clojupyter (0.4.321)
```

Or you can run in jupyter lab (from this repo):

```
jupyter lab
```

then open a file like: examples/demo-clojupyter.ipynb and run all cells.

## Use clojupyter as a library as part of another program/library

You can also use this as a library - here's an example: https://github.com/krukow/edmondson

**Comment by krukow** [comment]
Closing: I will not be able to support releasing to Conda and all users should be familar with clojars since this is a clojure project.
