### ISSUE TITLE
consider to publish/release uberjars

### ISSUE THREAD

**Issue by behrica** [clojupyter/clojupyter#181]
Would you consider to release the uberjars somewhere ?
This would make certain" automatic installations" easier.
Currently I need to "build" the uberjar in the docker:

https://github.com/behrica/binder-clojupyter/blob/master/Dockerfile

**Comment by krukow** [comment]
Yeah I can do that via GitHub releases: https://github.com/clojupyter/clojupyter/releases/tag/v0.4.332
