### ISSUE TITLE
I've just made a Docker image for this.

### ISSUE THREAD

**Issue by kxxoling** [clojupyter/clojupyter#26]
I've just made a Docker image for this, could make the installation progress simpler: https://github.com/kxxoling/jupyter-clojure-docker

**Comment by pdenno** [comment]
This looks interesting! I'm just learning about Docker. Would there be a different version of this file were one to use anaconda python? A different version for a different version of linux?

**Comment by roryk** [comment]
That's great! Could you add to the documentation that option for installing?

**Comment by kxxoling** [comment]
@pdenno Anaconda Python is used by Jupyter official image, which is based on Debian. I could change it to Anaconda Python, but I can't find any benifit from it. Different Linux is considerable, but it would take time to have a trial.

@roryk I'm happy to see this helps. I would create a Pull Request soon. :)

**Comment by klausharbo** [comment]
The Docker image is mentioned in the main README, so it seems to me we don't need this issue any more.
