### ISSUE TITLE
kernel registration

### ISSUE THREAD

**Issue by janezj** [clojupyter/clojupyter#38]
"make install" installs kernel for current user only. So in multiuser environment - **jupyterhub** the kernel is not visible for other users.

There is an example of docker image bellow when notebook is started as root, there are 3 kernels (r, python3, clojure). When started as jupyterhub only python and r kernel are available.

## Dockerfile
-----------------
```
FROM continuumio/anaconda3:latest

ENV LEIN_ROOT=1

# Install prerequisites
RUN apt-get update && apt-get install -y gcc default-jre make vim tmux 
RUN conda install -y -c r r-essentials r-rjava
RUN conda install -y -c conda-forge jupyterhub=0.7.2

# clojure
RUN wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/bin/lein && chmod +x /usr/bin/lein
RUN lein self-install

RUN git clone https://github.com/roryk/clojupyter

WORKDIR clojupyter
RUN make && make install
WORKDIR /

RUN useradd --create-home --shell /bin/bash admin
RUN echo "1234\n1234"  | passwd admin
```

## start jupyterhub
start jupyterhub from docker image shell. 
`jupyterhub --PAMAuthenticator.create_system_users=True --PAMAuthenticator.admin_users="{'admin'}" `

**Comment by pdenno** [comment]
I built a docker image similarly. Started it with docker run -i -t docplex /bin/bash
and then used the jupyterhub command you suggest. How do I talk to the server?

**Comment by klausharbo** [comment]
This issue appears to be obsolete.  Closed.
