### ISSUE TITLE
Adding com.amazonaws/aws-java-sdk "1.11.147" fails

### ISSUE THREAD

**Issue by rebcabin** [clojupyter/clojupyter#41]
Hello --- 
I added one line to project.clj, namely

    [com.amazonaws/aws-java-sdk "1.11.147"]

building and running unit tests in emacs cider succeeds, but I cannot open a clojure kernel. Here is the output of a build & run cycle

```
$ pushd && make && make install && pushd && jupyter-notebook
~/Documents/clojupyter ~/Documents ~
lein uberjar
Compiling clojupyter.core
Compiling clojupyter.core
Created /Users/bbeckman/Documents/clojupyter/target/clojupyter-0.1.0-SNAPSHOT.jar
Created /Users/bbeckman/Documents/clojupyter/target/clojupyter-0.1.0-SNAPSHOT-standalone.jar
cat bin/clojupyter.template $(find . -maxdepth 2 -type f | grep -e ".*standalone.*\.jar") > bin/clojupyter
chmod +x bin/clojupyter
mkdir -p ~/.ipython/kernels/clojure
cp bin/clojupyter ~/.ipython/kernels/clojure/clojupyter
~/Documents ~/Documents/clojupyter ~
[W 13:26:13.576 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 13:26:13.991 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 13:26:13.996 NotebookApp] Serving notebooks from local directory: /Users/bbeckman/Documents
[I 13:26:13.996 NotebookApp] 0 active kernels 
[I 13:26:13.996 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=a8bc42cf2609dfed1d12f9a32a1b23961dab47532123489e
[I 13:26:13.996 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:26:13.997 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a8bc42cf2609dfed1d12f9a32a1b23961dab47532123489e
[I 13:26:14.304 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 13:26:31.632 NotebookApp] Kernel started: 558d1e54-7207-4b28-973d-b552e5de4de5
Error: Invalid or corrupt jarfile /Users/bbeckman/.ipython/kernels/clojure/clojupyter
```

If I take out the dependency on amazonaws and rebuild in project.clj, everything goes back to normal. 

I have been able to add other libraries like manifold and neanderthal. There is just something about the amazonaws one.

Please keep up the good work, clojupyter is great and important!

**Comment by rebcabin** [comment]
I found that `[com.amazonaws/aws-java-sdk "1.10.77"]` DOES produce an OK uberjar. also that 1.11.148 does NOT produce OK uberjar.

**Comment by rebcabin** [comment]
I found a solution that works in Clojupyter, but only by using deprecated APIs from Amazon. Here is something that will list your tables (not guaranteed minimal or best, nor guaranteed to be using the most recent versions that clojupyter can handle; rather, I did a binary search for the first one that would work using the two required Java packages):

In clojupyter's project.clj

    [com.amazonaws/aws-java-sdk "1.10.75"]
    [org.apache.httpcomponents/httpclient "4.5.2"]

In some cells in clojupyter:

```
(import 'com.amazonaws.services.dynamodbv2.AmazonDynamoDB)
(import 'com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient)
;;; The following is not available in 1.10.75, the version I use with Clojupyter.
#_(import 'com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder)
(import 'com.amazonaws.services.dynamodbv2.model.ListTablesRequest)
(import 'com.amazonaws.services.dynamodbv2.model.ListTablesResult)
(import 'com.amazonaws.auth.profile.ProfileCredentialsProvider)
```

```
(let [client (-> (ProfileCredentialsProvider.)
                 (AmazonDynamoDBClient.)
                 (.withEndpoint "https://dynamodb.us-east-1.amazonaws.com"))
      lastEveluatedTableName nil]
    (let [listTablesRequest (-> (ListTablesRequest.)
                                (.withLimit (java.lang.Integer. 10))
                                (.withExclusiveStartTableName lastEveluatedTableName))]
        (let [result (.listTables client listTablesRequest)]
            (println (-> result (.getTableNames) (.size))
                     ))))
```

**Comment by bradfordboyle** [comment]
It looks like you were trying to compile the AWS SDK into clojupyter. If you're just trying to use the SDK from a notebook, you should be able to do this (taken from the [leiningen FAQ](https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md))

```clojure
;; add if you get 'Tried to use insecure HTTP repository without TLS'
;; your may or may not need to add the following
;; never do this
(require 'cemerick.pomegranate.aether)
(cemerick.pomegranate.aether/register-wagon-factory!
 "http" #(org.apache.maven.wagon.providers.http.HttpWagon.))

(helper/add-dependencies '[com.amazonaws/aws-java-sdk "1.11.297"])
```

**Comment by klausharbo** [comment]
It appears that the recent upgrade to Clojure 1.10 may have fixed the issue rebcabin raised initiailly, at least I am able to compile the current version of clojupyter with the dependency `[com.amazonaws/aws-java-sdk "1.11.147"]` (mentioned in the initial post).

These days I believe the most common way to talk to AWS using Clojure is either to use [`amazonica`](https://github.com/mcohen01/amazonica) or, announced quite recently, Cognitect's [`aws-api`](https://github.com/cognitect-labs/aws-api).  I have very good experiences with the formed but haven't tried `aws-api` as yet.  Admittedly, I haven't tried any of them in combination with clojupyter, but would expect it to work.

I think the general solution to fixing issues such as this is to enable clojupyter to connect to a running Clojure process using nREPL.  Hopefully I'll be able to add this feature to clojupyter some time in the not-too-distant future.
