### ISSUE TITLE
Create a clojupyter project

### ISSUE THREAD

**Issue by didiercrunch** [clojupyter/clojupyter#50]
I feel very bad of asking but would it be possible to create a github organization dedicated to clojupyter?  The goal would be to have all the jupyter projects under the same directory.  I believe for now there is only https://github.com/didiercrunch/lein-jupyter but it is easy to see the necessity to add a boot-jupyter. 

I believe that very shortly we could have 4 repos in this organisation.

*  https://github.com/clojupyter/clojupyter
* https://github.com/clojupyter/lein-jupyter
* https://github.com/clojupyter/boot-jupyter
* https://github.com/clojupyter/website

In this fashion, we could create a nice web page dedicated to the project and add traction to the project.  We have an outstanding product here (thanks to @roryk ) and we need to shout it to the world!

cheers,

didier

**Comment by roryk** [comment]
Hi @didiercrunch,

Great idea! I added everybody to the organization and transferred the repo over. Thanks everyone!

**Comment by roryk** [comment]
Let me know if you want me to swap anything in the group settings, I just used the default settings and turned on everybody can write/push/whatever to any repository if they are in the group, since that is what we're doing here.

**Comment by didiercrunch** [comment]
I believe everything is good.  I have already transfered lein-jupyter.

thousand thanks for that.

cheers!

didier

2018-01-24 9:23 GMT-05:00 Rory Kirchner <notifications@github.com>:

**Comment by roryk** [comment]
Anytime!
