### ISSUE TITLE
Create a website for marketing purposes

### ISSUE THREAD

**Issue by didiercrunch** [clojupyter/clojupyter#53]
Let's create a website to attract more users and make the documentation and example easier to read.  I have created a [repository](https://github.com/didiercrunch/clojupyterwebsite) on my personal page to test something.  The website is exposed as a github page [here](https://didiercrunch.github.io/clojupyterwebsite/).

I propose to use http://nbviewer.jupyter.org to render the notebooks.  It does an outstanding jobs ([example](http://nbviewer.jupyter.org/github/didiercrunch/graphly/blob/master/geom.ipynb))

**Comment by didiercrunch** [comment]
I propose https://github.com/didiercrunch/clojupyterwebsite/blob/master/docs/images/clojupyter-logo.svg as logo.

**Comment by aria42** [comment]
Nice! You could also just rotate the organge parantehsis on top and bottom of the `jupyter`logo so they look like parens :)

My only serious comment is you might want to change the color on the header banner since it makes it hard to see the logo.

**Comment by didiercrunch** [comment]
I am actually colour blind.  I'll need help of a friend on that one.

**Comment by didiercrunch** [comment]
And just to be sure we understand each other, the website will point users to "lein-jupyter" as the easiest entry point?

**Comment by roryk** [comment]
![image](https://user-images.githubusercontent.com/414586/35519704-f814ca0c-04e2-11e8-8d85-f7024f84285f.png)
?

**Comment by pdenno** [comment]
That's so clever! I love it!

**Comment by didiercrunch** [comment]
I believe we have a logo!

I will attend a design session at my local library next saturday to make a
"pretty" web site.

Stay tuned.

**Comment by didiercrunch** [comment]
I believe this is a start.  The text is too small.  But hey, that is 10 minute work!


https://github.com/didiercrunch/clojupyterwebsite/blob/master/resources/public/images/clojupyter-logo-alpha-1.svg

**Comment by roryk** [comment]
cool, that looks awesome!

**Comment by roryk** [comment]
We should definitely use the logo @didiercrunch made on the main page, it is so nice.

**Comment by klausharbo** [comment]
Closing issue.
