### ISSUE TITLE
Enable CI for clojupyter

### ISSUE THREAD

**Issue by luojieshun** [clojupyter/clojupyter#55]
I think a green icon on readme is always comforting and is good for marketing ( showing things are working, hopefully : ) ).

Added a Travis CI ( free for open source project s) configuration file in an earlier PR but has no permission to add the web hook.

**Comment by roryk** [comment]
Hey Jieshun,

I clicked on the Travis CI integration so it should be all good, let me know if it isn't working.

**Comment by roryk** [comment]
Thanks! I clicked it on and added the badge. Soothing green it is.

**Comment by luojieshun** [comment]
Just submitted a PR. Works like a charm!
