### ISSUE TITLE
Update core.async dependency

### ISSUE THREAD

**Issue by sparkofreason** [clojupyter/clojupyter#63]
The version of core.async (0.2.395) used by clojupyter appears to be causing conflicts when used with projects requiring more recent versions (guessing post-0.4.*). The particular error observed was

```
java.lang.ClassNotFoundException: clojure.core.async.Mutex
```

**Comment by tirkarthi** [comment]
To add to this, the current version might also cause issues with Clojure 1.9. This is fixed with clojure/core.async@2f87bc7 . Consider upgrading to core.async-0.3.442 or later.

**Comment by klausharbo** [comment]
The dependency on core.async has been removed so its version should not be a problem any longer.
