### ISSUE TITLE
Maven repository url uses insecure HTTP instead of secure HTTPS

### ISSUE THREAD

**Issue by orolle** [clojupyter/clojupyter#64]
I git cloned this repo today (27th March 2018) and tried the getting started [example](https://github.com/aria42/clojupyter/blob/mime-improvements/examples/html-demo.ipynb), but I got a ssh wagon exception which underlies maven, which complained that it cannot establish a secure connection. It seems that the maven repository url uses HTTP. I applied the workaround below. 

Sadly I cannot reproduce the error anymore after I applied this workaround, because the required artifacts  `[org.clojure/data.json "0.2.6"]` is already in my local repository cache.

**Workaround**
```
;; WARNING: DISABLES TLS ENCRYPTION; INSECURE !!!
(require 'cemerick.pomegranate.aether)
(cemerick.pomegranate.aether/register-wagon-factory!
 "http" #(org.apache.maven.wagon.providers.http.HttpWagon.))
(helper/add-dependencies '[org.clojure/data.json "0.2.6"])
```

**Comment by clartaq** [comment]
Same problem trying to work through the Incanter example.

**Comment by bradfordboyle** [comment]
Can you see if PR66 fixes this issue for you?

**Comment by clartaq** [comment]
That fixed it for me. Thanks!
