### ISSUE TITLE
Incremental Output

### ISSUE THREAD

**Issue by ben-denham** [clojupyter/clojupyter#67]
Is there currently a way to incrementally update a cell's output? E.g. to provide a progress bar for some long-running background thread?

The closest I've come so far is the following snippet, which immediately prints "Let the above loop run in the background", but any calls to `display` after the cell has finished its initial output seem to be buffered until the next time the cell is executed:

```clojure
(require '[clojupyter.misc.display :refer [display]])
(future
    (doseq [i (range 10)]
        (Thread/sleep (* i 100))
        (display (str "Completed " i))))
(println "Let the above loop run in the background")
```

Also, thanks for the super useful kernel!

**Comment by luojieshun** [comment]
Have you tried println?

**Comment by klausharbo** [comment]
It is indeed possible to incrementally update a cell, as in

```
(doseq [i (range 10)]
    (println i)
    (Thread/sleep 500))
:ok
```
which will print numbers 0-9 and finally return `:ok` as the result of evaluation.
