### ISSUE TITLE
FileNotFoundException Could not locate... on classpath. 

### ISSUE THREAD

**Issue by DVious** [clojupyter/clojupyter#69]
Hi,

Why does your sample code work for me:

```
(require '[clojupyter.misc.helper :as helper])

​

(helper/add-dependencies '[org.clojure/data.json "0.2.6"])

(require '[clojure.data.json :as json])
```

​But, a cut/paste to my repo library always returns this:

`(require '[clojupyter.misc.helper :as helper])

(helper/add-dependencies '[uk.org.russet/tawny-owl "1.6.1"])

(require '[uk.org.russet/tawny-owl])

​

FileNotFoundException Could not locate tawny_owl__init.class or tawny_owl.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.  clojure.lang.RT.load (RT.java:456)

                RT.java:   456 clojure.lang.RT/load                                   
               core.clj:  5893 clojure.core$load$fn__5677/invoke                      
               core.clj:  5892 clojure.core$load/invokeStatic                         
               core.clj:  5876 clojure.core$load/doInvoke                             
            RestFn.java:   408 clojure.lang.RestFn/invoke                             
               core.clj:  5697 clojure.core$load_one/invokeStatic                     
               core.clj:  5692 clojure.core$load_one/invoke                           
               core.clj:  5737 clojure.core$load_lib$fn__5626/invoke                  
               core.clj:  5736 clojure.core$load_lib/invokeStatic                     
               core.clj:  5717 clojure.core$load_lib/doInvoke                         
            RestFn.java:   142 clojure.lang.RestFn/applyTo                            
               core.clj:   648 clojure.core$apply/invokeStatic                        
               core.clj:  5774 clojure.core$load_libs/invokeStatic                    
               core.clj:  5758 clojure.core$load_libs/doInvoke                        
            RestFn.java:   137 clojure.lang.RestFn/applyTo                            
               core.clj:   648 clojure.core$apply/invokeStatic                        
               core.clj:  5796 clojure.core$require/invokeStatic                      
            RestFn.java:   408 clojure.lang.RestFn/invoke                             
                     []:     2 user$eval6295/invokeStatic                             
               core.clj:  3105 clojure.core$eval/invokeStatic                         
               core.clj:  3101 clojure.core$eval/invoke                               
               main.clj:   240 clojure.main$repl$read_eval_print__7408$fn__7411/invoke
               main.clj:   258 clojure.main$repl$fn__7417/invoke                      
               main.clj:   174 clojure.main$repl/doInvoke                             
            RestFn.java:  1523 clojure.lang.RestFn/invoke                             
               AFn.java:   152 clojure.lang.AFn/applyToHelper                         
               AFn.java:   144 clojure.lang.AFn/applyTo                               
               core.clj:   646 clojure.core$apply/invokeStatic                        
               core.clj:  1881 clojure.core$with_bindings_STAR_/invokeStatic          
            RestFn.java:   425 clojure.lang.RestFn/invoke                             
               AFn.java:    22 clojure.lang.AFn/run                                   
ThreadPoolExecutor.java:  1149 java.util.concurrent.ThreadPoolExecutor/runWorker      
ThreadPoolExecutor.java:   624 java.util.concurrent.ThreadPoolExecutor$Worker/run     
            Thread.java:   748 java.lang.Thread/run                                   

`

The add-dependencies function will pull in the library, where I've previously wiped it - it's just that any reference to the library fails to be found on the classpath.

I'm running the examples using labx/beakerx and specifying, to beakerx:
`javac -cp   /Users/.../.m2/repository/uk/org/russet/tawny-owl/1.6.1`

The solution is so obvious, it evades me.  Any help appreciated.

**Comment by nataliefreed** [comment]
I have the same question. Did you ever figure this out?

**Comment by DVious** [comment]
No!  After many lost hours, I'm back to straight coding in proto-repl IDE.  

I'm a developer, not a scientist.  I don't think that it was good for me, juggling conda, panda, python, this and that, just to _try_ and get an environment, that is half as useful, to me, as proto-repl.

In fact, apart from the idea of the text cell, there wasn't much in it for me.

**Comment by klausharbo** [comment]
I took a quick look at this: The `require` for you show does not look quite right.  It seems to work in the current version of clojupyter, like this:

```
(require '[clojupyter.misc.helper :as helper])
(helper/add-dependencies '[uk.org.russet/tawny-owl "1.6.1"])
(require '[tawny.owl :as owl])
```

-Klaus.
