### ISSUE TITLE
rendering vega-lite inline

### ISSUE THREAD

**Issue by keesterbrugge** [clojupyter/clojupyter#75]
Hi,

Thanks for your work on this kernel.

Currently I mostly use ggplot in R for visualisations. I would love to have vega-lite available to me in a notebook environment with clojure.

In the ipython kernel a vega-lite spec can be rendered inline as follows

```python
from IPython.display import display

display({
    "application/vnd.vegalite.v2+json": {
        "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
        "description": "A simple bar chart with embedded data.",
        "data": {
            "values": [
                {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
                {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
                {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
            ]
        },
        "mark": "bar",
        "encoding": {
            "x": {"field": "a", "type": "ordinal"},
            "y": {"field": "b", "type": "quantitative"}
        }
    }
}, raw=True)
```
Does similar functionality exist in clojupyter?

**Comment by metasoarous** [comment]
Yes, I'm working on support for this in oz, but I'm having trouble getting `clojupyter.misc.helper/add-javascript` to work (see #76). Any thoughts on this?

**Comment by metasoarous** [comment]
@jtcbrule I'm not sure how exactly, but I missed your comment the other day (or failed to come back to it for some reason). I'll see if I can't get this to work. Thanks for sharing!

**Comment by metasoarous** [comment]
I've taken @jtcbrule's code and adapted it somewhat into the `oz.notebook.clojupyter` ns of oz. I just updated the snapshot release `[metasoarous/oz "1.5.0-SNAPSHOT"]` if anyone would be so kind as to give it a whirl and let me know whether it works for you. Thanks in advance.

**Comment by keesterbrugge** [comment]
requiring oz in clojupyter didn't work for me, see https://github.com/metasoarous/oz/issues/33#issuecomment-456050714
