### ISSUE TITLE
Update Clojure version

### ISSUE THREAD

**Issue by metasoarous** [clojupyter/clojupyter#77]
I believe the problems I'm having with getting an oz (Vega & Vega-Lite viz) plugin for Clojupyter working (see metasoarous/oz#33) may have to do with Clojure 1.8 not having vars in clojure.core defined which are expected by some of Oz's dependencies. I may have a work around for this (will let you know how it goes), but is there a reason Clojupyter is still on 1.8? If not would you consider updating to either 1.9 or 1.10? I _think_ this would solve my problem, and avoid an ugly workaround in Oz.

Thanks in advance.

**Comment by roryk** [comment]
Thank you, sorry for not responding to this in a timely fashion. The community stepped up and implemented support for 1.10 so this should fix your problem.

**Comment by metasoarous** [comment]
Amazing! Thank you.
