### ISSUE TITLE
Meta issue about issues

### ISSUE THREAD

**Issue by roryk** [clojupyter/clojupyter#82]
I/we could use a hand cleaning out the old issues, are there any that we've covered recently and are closeable or otherwise addressable? Folks actually using clojuypter will have a better idea than I will. :)

**Comment by klausharbo** [comment]
Clearing out sounds like a good idea.   I don't mind helping out but won't make any promises as to how much I'll get done.  It looks I don't have sufficient privileges to close issue, though...

-Klaus.

**Comment by klausharbo** [comment]
Closed.
