### ISSUE TITLE
Consider the silent and store_history keys of an execute request

### ISSUE THREAD

**Issue by dzop** [clojupyter/clojupyter#85]
It seems the `silent` and `store_history` keys in an `execute_request` are not considered in the `execute-request-handler`

https://github.com/clojupyter/clojupyter/blob/a0a49c8346cfbaa6da01886b4c3f8a06ff078ad1/src/clojupyter/misc/messages.clj#L245

If `silent` is provided, then no `execute_input` or `execute_result` message should be emitted and `store_history` should be set to `false`.

Also if `store_history` is false then the code should not be added to the history.

Finally, from the Jupyter spec:

```
In order to obtain the current execution counter for the purposes of displaying input prompts, 
frontends may make an execution request with an empty code string and silent=True.
```
which implies that when `silent` is `true`, the following line shouldn't be evaluated

https://github.com/clojupyter/clojupyter/blob/a0a49c8346cfbaa6da01886b4c3f8a06ff078ad1/src/clojupyter/misc/messages.clj#L281

See the [Jupyter spec](https://jupyter-client.readthedocs.io/en/stable/messaging.html#execute) for more details

**Comment by klausharbo** [comment]
This is implemented on the `develop` branch.
