### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by klausharbo** [clojupyter/clojupyter#86]
I think the clojupyter repo would be easier to use if **relevant revisions were tagged as
releases**. Is there any particular reason why none have been tagged so far?

Following the version numbers in `project.clj` over time, and using the principle to consider *the
last `-SNAPSHOT` revision before a version bump* a 'release', it looks like the following releases
could be tagged :

'Release' | Revision   | Date         | Commit text|
:---------|:-----------|:-------------|:-------------------------------------------------
v0.1.0    | `f29096b3` | 2017-10-22   | *Cleaned up dependencies and release version 0.1.0.*
v0.1.1    | `642e6b39` | 2018-01-23   | *Merge pull request #48 from didiercrunch/master*
v0.1.2    | `bb0aecf7` | 2018-01-26   | *Add branch notebook links*
v0.2.0    | `994f680c` | 2018-12-03   | *Correct require -> :require and :import syntax (#73)*

The version number current `HEAD` of `master` is `v0.2.1-SNAPSHOT`, and it might also be considered a release:

'Release' | Revision   | Date         | Commit text|
:---------|:-----------|:-------------|:------------------------------------------------
v0.2.1    | `a0a49c83` | 2018-03-02   | *Support Clojure v1.10, nREPL 0.5.3, enable nrepl connections from editors (#79)*

If so, the version number in `project.clj` for `HEAD` should be renamed `0.2.2-SNAPSHOT` since it is
currently one revision further towards the next release.  If not, the last tagged release would be
`v0.2.0` and the version number would not need to be bumped.  I think it would make sense to
consider it a release, though.

Opinions?

-Klaus.

**Comment by butuzov** [comment]
I just came here to grab one of the tar.gz files instead cloning from the releases tab. So yeah... its' not only make things easier for maintaining, but it also will make my life a bit easier =).

**Comment by klausharbo** [comment]
I have tagged the versions as outlined above.
