### ISSUE TITLE
Support conda install on Mac, Linux, and Windows

### ISSUE THREAD

**Issue by klausharbo** [clojupyter/clojupyter#92]

**Comment by klausharbo** [comment]
I now have a working prototype enabling `conda install` on all 3 platforms.  Code still very prototypish.

**Comment by klausharbo** [comment]
I am working to prepare a release supporting Conda install of Clojupyter directly using `conda install clojupyter`, without having to get Clojure and compile/install Clojupyter itself.  Linux, MacOS, and Windows all supported.  Still working on tests and documentation.  Just pushed code to branch `release/conda-build`.  Excerpt of `Changelog.md`:

* Add support for `conda install` of Clojupyter supporting installs on Linux, MacOs, and Windows
  * Make implementation of installation more flexible to support both local installs, building Conda
    packages, and installing the Clojupyter conda package on end-user machine
  * Eliminate all Unixy dependencies as shell scripts, use Java and Clojupyter jarfile for all
    build/install/uninstall operations
  * Build Conda packages for Linux, MacOS, and Windows
  * Install and remove Clojupyter on end-user machines directly using Conda on Linux, MacOS, and Windows.
    * Install: `conda install -c simplect clojupyter` (not deployed to Anaconda cloud as yet)
	* Remove: `conda remove clojupyter`
* Add support for using Clojupyter as a library where resulting standalone jar knows how to install
  itself as a Jupyter kernel
  * Covers part of the functionality of `lein-jupyter` without dependency on Leiningen
* Improve and extend command line interface
  * Control the kernel identifier shown in Jupyter Lab and Notebook
  * List, remove, and install Clojupyter kernels using the command line interface
  * Build an application and use the Clojupyter command line interface to install and run it

There are many variables so initial versions may need some work before it's dependable.  Help testing will be much appreciated - anyone interested let me know.

-Klaus.

**Comment by pdenno** [comment]
Hi Klaus,

I use Anaconda and would be happy to help test this. I have all three of 
Linux Mint, MacOS, and Windows 10.

Best regards,
   Peter

**Comment by klausharbo** [comment]
Peter's experiments indicate that a preliminary set of test conda packages appear to work on his machines.  As mentioned above it is still a work-in-progress, but if you want to try them out, one of the commands below should install a snapshot version of the coming release

```
conda install -c simplect clojupyter
conda install -c simplect clojupyter=0.2.3snapshot
conda install -c simplect clojupyter=0.2.3snapshot=1
```

The result should be a new kernel in Jupyter Lab and Notebook.  `conda remove clojupyter` should work as well, and remove the kernel directory created in the conda setup.  You'll need to have conda/Anaconda installed (the recommended way to install Jupyter), obviously.

Packages available for `linux-64`, `osx-64` and  `win-64`.

Please report on experiences, good and bad, to this thread.

-Klaus.

**Comment by klausharbo** [comment]
Clojupyter 0.2.3alpha1 is now available.  It provides the ability to install Clojupyter using conda on Linux, MacOS, and Windows, adds a command line interface for controlling installed Clojupter kernels, and the ability to use Clojupyter as a library in any project.  0.2.3alpha1 is also available on [Clojars](www.clojars.org).

Closing this issue.
