### ISSUE TITLE
Using python in the same notebook as Clojure

### ISSUE THREAD

**Issue by jefffriesen** [clojupyter/clojupyter#93]
This may be unrealistic, but is it possible to run Python in the same notebook as Clojure? I'm working with Python libs that are unavoidable, but it would be nice to do the rest of the data transformations in Clojure. 

I realize this may only work with GraalVM, but that may be a really interesting approach. Is this unlikely?

Thanks

**Comment by daslu** [comment]
@jefffriesen, you may wish to look into this [new project](https://github.com/cnuernber/libpython-clj) by @cnuernber, writing a library for calling Python from Clojure. Note this is work in progress, so I guess testing it on your use cases could be very helpful.

See more updates and discussions of this under the [python interop topic](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/python.20interop) of the [data-science stream](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science) at the Clojurians Zulip chat.

In the near future, another option for actually writing Python and Clojure in the same notebook could be polyglot notebooks such as:
- Jupyter-based [SoS](https://vatlab.github.io/sos-docs/) - does not support Clojure yet
- [Rstudio notebooks](https://rmarkdown.rstudio.com/lesson-10.html) - will support Clojure soon

**Comment by jefffriesen** [comment]
@daslu I will check out all of these links. Thanks for the great response! I'll close this ticket.
