### ISSUE TITLE
Specifying dependencies in Clojupyter with deps.edn

### ISSUE THREAD

**Issue by jtcbrule** [clojupyter/clojupyter#94]
Is it possible to specify libraries with deps.edn / is it possible to modify the Clojupyter kernel to support this? I'm imagining a use case where someone installs the Clojupyter kernel and creates a new project foobar:

    foobar
    ├── examples.ipynb
    └── deps.edn

And is able to list their dependencies in deps.edn, which can then be normally `require`d in the notebook.

I think the main advantage would be ease-of-use for newcomers/end users and more "seamless" transitions between notebooks and normal .clj source files (wouldn't have to rely on e.g. Leiningen or `helper/add-dependencies`)

**Comment by klausharbo** [comment]
Hi Joshua -

I am working to release v0.2.3 of Clojupyter which I believe supports something along the lines of what you want.  The functionality is currently available as `0.2.3-ALPHA1`; the documentation of how to build and install a custom Clojupyter kernel (ie. one with libraries or application code built in at startup) is described in [Using Clojupyter as a library](https://github.com/clojupyter/clojupyter/blob/release/0.2.3alpha1/doc/library.md) (on the 0.2.3-ALPHA1 branch).  You may also want to look at [Usage Scenarios](https://github.com/clojupyter/clojupyter/blob/release/0.2.3alpha1/doc/usage-scenarios.md) which provides some context.

The implementation depends only on Clojure's command line interface and so should work with both tools.deps, Leiningen and Boot.

I believe the current documentation references 0.2.3-SNAPSHOT, substituting 0.2.3-ALPHA1 should work, but here's an example of how one way to do it:

Directory contents:
```
> tree .
.
├── deps.edn
└── src
    └── user.clj

1 directory, 2 files
```
Deps.edn:

```
> cat deps.edn
{:deps {clojupyter {:mvn/version "0.2.3-ALPHA1"}}
 :aliases {:depstar {:extra-deps {seancorfield/depstar {:mvn/version "0.3.0"}}}}}
```

user.clj:

```
> cat src/user.clj
(ns user (:require [clojupyter.kernel.version :as ver]))

(defn custom-version []
  (str "Long version string: " (ver/version-string-long)))
```

Build uberjar using Depstar:

```
> clojure -A:depstar -m hf.depstar.uberjar mykernel.jar
Building uber jar: mykernel.jar
{:warning "clashing jar item", :path "META-INF/sisu/javax.inject.Named", :strategy :noop}
...
```
(I haven't looked into why this generates warnings as yet)

What kernels are installed?

```
> clj -m clojupyter.cmdline list-installs
Clojupyter v0.2.3-ALPHA1 - All Clojupyter kernels

    No kernels match ''.

exit(1)
```
No kernels installed.

Install kernel:

```
> clj -m clojupyter.cmdline install --ident mykernel --jarfile mykernel.jar
Clojupyter v0.2.3-ALPHA1 - Install local

    Installed jar:	mykernel.jar
    Install directory:	~/Library/Jupyter/kernels/mykernel
    Kernel identifier:	mykernel

    Installation successful.

exit(0)
```
List kernels:
```
> clj -m clojupyter.cmdline list-installs
Clojupyter v0.2.3-ALPHA1 - All Clojupyter kernels

    |    IDENT |                                DIR |
    |----------+------------------------------------|
    | mykernel | ~/Library/Jupyter/kernels/mykernel |

exit(0)
```

You should now be able to call `user/custom-version` at startup (select kernel `mykernel` in the kernel list).

Do follow up if something doesn't work for you.

-Klaus.

**Comment by jtcbrule** [comment]
Thanks for the info.

My original thinking was being able to conda install Clojupyter and then specify deps from a deps.edn file is a "low friction" way for end users to get started - conda installation is an amazingly straightforward way for newcomers to get started, but the downside is that they can't experiment with other libraries.

"Clojupyter as a library" is cool since it seems like it's the Clojure version of Python Jupyter notebooks with virtualenv; good for reproducibility, but harder for newcomers to understand.

I think a "best of both worlds" approach would be if the generic (conda or pip installable) Clojuptyter kernel automatically resolved dependencies from whatever deps.edn file was on the path where it was started and made them available on the CLASSPATH. (Of course, there may be excellent reasons why this is too complex / not a good idea; I'm just trying to get a feel for the relative difficulty of updating Clojupyter to support this.)

**Comment by klausharbo** [comment]
I see what you mean.  The conda support is brand new, not even released yet (soon, hopefully), and my focus for providing was indeed to lower to barrier to entry to using Clojupyter.  Since you can load any library in your notebook, to gain something I suppose you'd want the extar libraries to link *before* kernel startup, and that, I think, would mean at kernel *install* time.  I think that would be doable, but I'm concerned to add much complexity to the conda install as any Clojure-related install/linking problems would be really tricky to debug as they will occur deep in the bowels of conda linking: The conda-installing user might have a hard time figuring out what went wrong with conda being an extra layer of things going on.

So, for now at least, I think the wise thing to do is to keep the conda install simple and recommend users who want to custom kernel to build one using an approach something like what I outlined above.  I think that people who will want to add extra libraries will have a reasonable understanding of Clojure anyway and so (hopefully) will find building a custom kernel using Clojupyter as a library to be a fairly straightforward exercise.  If conda installing Clojupyter turns out to be popular more features, like the one you propose, could become relevant.

Thanks for your input,

-Klaus.

**Comment by klausharbo** [comment]
Reflecting on this a bit more: My primary objective for adding support for conda install was to make it easier to try out Clojure in Jupyter *and* to make that experience available for Windows users.  For now I think priority should go to making the basic install reliable, thereby protecting the experience of the user who uses Jupyter and is curious to try out Clojure/Clojupyter.  Until conda installing is shown to be reliable by end users using it with success I think priority needs to go to maturing the basic functionality of installing generic kernels.

**Comment by pdenno** [comment]
Clojupyter loads pomegranate https://github.com/cemerick/pomegranate to 
handle dynamic loading of libraries.

I have not used deps.edn. I suppose it could be used with pomegranate 
for run-time loading.

**Comment by klausharbo** [comment]
Joshua's original post stipulated *not* relying on `clojupyter.misc.help/add-dependencies` - it uses pomegranate for loading.

**Comment by pdenno** [comment]
Oops. I see. Interesting.

**Comment by klausharbo** [comment]
Clojupyter 0.3.0beta1 used tools.deps.  Closed.
